"""add user table

Revision ID: 8a31a44b3bb6
Revises: 
Create Date: 2024-10-17 08:32:26.317724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a31a44b3bb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Usuario', sa.String(), nullable=False),
    sa.Column('NUsuario', sa.String(), nullable=True),
    sa.Column('Delegacion', sa.String(), nullable=True),
    sa.Column('SubDelegacion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    with op.batch_alter_table('FicherosSolares', schema=None) as batch_op:
        batch_op.alter_column('idFichero',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('Fichero')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('FicherosSolares', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Fichero', sa.BINARY(length=2000), autoincrement=False, nullable=True))
        batch_op.alter_column('idFichero',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=1, increment=1),
               existing_nullable=False,
               autoincrement=True)

    op.drop_table('usuarios')
    # ### end Alembic commands ###
